spring:

  kafka:

    bootstrap-servers: localhost:9092

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:

      enable-auto-commit: true
      auto-offset-reset: earliest
      auto-commit-interval: 5000

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: com.erhernandez.kafka.dto
        spring.json.value.default.type: com.erhernandez.kafka.dto.Order

logging:

  level:

    root: INFO

    com.erhernandez.kafka: INFO

    org.springframework.kafka: INFO

    org.apache.kafka: WARN