spring:
  kafka:

    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      
      properties:

        schema.registry.url: http://localhost:8085

        auto.register.schemas: true

    consumer:
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer



logging:

  level:

    root: INFO

    com.erhernandez.kafka: INFO

    org.springframework.kafka: INFO

    org.apache.kafka: WARN